### ISSUE TITLE
check for rustfmt 'correctness' in CI

### ISSUE THREAD

**Issue by Licenser** [simd-lite/simdjson-rs#43]
We should make sure in CI that rustfmt was run before merging.

**Comment by sunnygleason** [comment]
awesome idea! is it something like this?

![image](https://user-images.githubusercontent.com/153621/64386186-70a8c280-d006-11e9-8495-d7f9a40a460e.png)

**Comment by Licenser** [comment]
👍 great find

**Comment by sunnygleason** [comment]
all set! 😄 🎉

**Comment by sunnygleason** [comment]
fixed by #44
