### ISSUE TITLE
consider code coverage codecov.io/other?

### ISSUE THREAD

**Issue by sunnygleason** [simd-lite/simdjson-rs#45]
Would it be interesting to integrate something like this?

https://github.com/codecov/example-rust
https://users.rust-lang.org/t/test-coverage-with-grcov/24851
https://sunjay.dev/2016/07/25/rust-code-coverage

(Not that it's religiously followed, but at least gives a
rough indication of areas that might be missed?)

**Comment by Licenser** [comment]
Absolutely! (I admit I just never got that working :joy:)

**Comment by sunnygleason** [comment]
implemented by #51 ... 🎉
