### ISSUE TITLE
Any chance to port to serde_json

### ISSUE THREAD

**Issue by pickfire** [simd-lite/simdjson-rs#47]
Is it possible to improve existing serde_json without splitting it out as simdjson?

https://github.com/serde-rs/json/issues/120

**Comment by Licenser** [comment]
Doubtful.

simdjson and serde_json have fundamentally different goals and philosophies. simdjson focuses most and foremost on high performance sind_json has other priorites, such as portability so there is an underlying disconnect between the two.

But for what it's worth simd_json implements support for serde traits so it can be used very much as a drop in replacement in most places - and when not it is likely an oversight / bug :)

**Comment by pickfire** [comment]
Maybe I should ping @dtolnay and see what he thinks.

**Comment by Licenser** [comment]
using the tape would be a easy way to get there but I don't think this will happen anytime soon so I'll close that issue for the time being feel free to re-open it if things change.
