### ISSUE TITLE
arch alignment & tracking upstream?

### ISSUE THREAD

**Issue by sunnygleason** [simd-lite/simdjson-rs#62]
I started on this pull request to get us closer to upstream structure, I think we're in a good place to pick it up again maybe?

#46 

@Licenser, what would you think about this idea:

* in the README/Cargo.toml description/etc, we add some description of `currently tracking simdjson vX.Y.Z`
* we finish that arch alignment to get the raw (current) codebase close in a majority sense (of course except for the necessary rust-specific enhancements)
* we genericise/template-enable the code that was made more similar by arch alignment (reducing the size of platform-specific modules)
* this should get the core features very close to the corresponding upstream version 🎉 

Very interested in your thoughts! 🥂

**Comment by Licenser** [comment]
👍 sounds good, the only thing with #46 was that we need to make sure we don't degrade performance.

**Comment by sunnygleason** [comment]
💯

**Comment by sunnygleason** [comment]
implemented by #80, #81, merged with #71
