### ISSUE TITLE
alloc_counter doesn't require nightly anymore

### ISSUE THREAD

**Issue by WildCryptoFox** [simd-lite/simdjson-rs#85]
@Licenser https://github.com/simd-lite/simdjson-rs/blob/f47a7ed781b26173132ab64af4b290cc8732d9e6/.github/workflows/tests.yml#L38

Prior to `0.0.4` `alloc_counter` did need nightly for documentation but was not required for functionality. This oversight has been resolved. You can test your allocations on the latest stable too.

**Comment by Licenser** [comment]
Awesome thanks!
