### ISSUE TITLE
Clarify README regarding jemalloc

### ISSUE THREAD

**Issue by denisfalqueto** [simd-lite/simdjson-rs#96]
The text says "... make sure to use jemalloc and not the system allocator (which has now become default in rust)". But it's not clear to me what is referred by "which". Is it jemalloc or the system allocator? I believe it only makes sense to be about jemalloc, so I propose moving the parenthesis remark to just after "jemalloc" name.

**Comment by Licenser** [comment]
Good point! We'll update the readme :)

the status is (to give a quick answer): 

* rust (by now) uses the system allocator, it tended to use jemalloc.
* simd-json benefits from jemalloc, or even better mimalloc.
